### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'receive_timeout'. On elasticbeanstalk

### ISSUE THREAD

**Issue by raydWF** [etianen/django-python3-ldap#128]
First off I can't start to explain how much this library supported me. Thanks for writing this!

I have a local app that is  using your library and it's working fine. But when I deploy it to AWS elastic beanstalk, it throws an error saying that
 `TypeError: __init__() got an unexpected keyword argument 'receive_timeout'.`

I was suspecting that my company's firewall was blocking the access to the LDAP server, but then I asked IT to monitor attempt to connect to the LDAP server and they said they didn't see any connections. I am quite confused what the issue might be. Also my `LDAP_AUTH_OBJECT_CLASS = "user"` isn't working as it returns all the objects instead of only the `user` objects.

I would really appreciate any input on any of the issues. Thanks again!

**Comment by etianen** [comment]
It looks like your EBS instance is missing something that's required to
compile the python-ldap library.

However, you also appear to be using two different ldap auth libraries!
django-python3-ldap does not need django-auth-ldap or python-ldap to be
installed at all!

**Comment by raydWF** [comment]
Thank you so much for your help! After debugging repeatedly I realized that apparently django-python3-ldap does not work with ldap3 version 2.3 on EBS? Anyways I changed the version number to 2.2.3 and it worked! 

I also have problem syncing the `user` object tho, I have set `LDAP_AUTH_OBJECT_CLASS = "user"` and confirmed that indeed that is what the object class is called but when I do `ldap_sync_users` is syncs all the objects. Is there something I might be doing wrong or anyway to customize filters? There are objects that have names that end with a `$`, those are the ones that I do not want to sync.

**Comment by etianen** [comment]
You can customize filters using the LDAP_AUTH_FORMAT_SEARCH_FILTERS setting.
The setting takes a path to a function that is used to compile the LDAP search filters.

The default implementation is here:
https://github.com/etianen/django-python3-ldap/blob/master/django_python3_ldap/utils.py#L116

You will probably want to define your own function that calls the default implementation, and adds your own filters:

``` py
# settings.py

LDAP_AUTH_FORMAT_SEARCH_FILTERS = "your_app.ldap.format_search_filters"

# your_app/ldap.py

from django_python3_ldap.utils import format_search_filters as format_search_filters_base

def format_search_filters(ldap_fields):
    search_filters = format_search_filters_base(ldap_fields)
    search_filters.append("YOUR ADDITIONAL FILTER HERE")
    return search_filteres
```

I don't know the correct syntax for filtering based on a field ending with "$". That's an exercise for you. :)
